#
# Fonts here are ordered triplets of min. population, file name, font size.
#
FONTS_Z4=  0 fonts/Arial.ttf 10   250000 fonts/Arial.ttf 12
FONTS_Z5=  0 fonts/Arial.ttf 10   2500000 fonts/Arial.ttf 12
FONTS_Z6=  0 fonts/Arial.ttf 10   250000 fonts/Arial.ttf 13   2500000 fonts/Arial.ttf 18
FONTS_Z7=  0 fonts/Arial.ttf 10   250000 fonts/Arial.ttf 13   2500000 fonts/Arial.ttf 18
FONTS_Z8=  0 fonts/Arial.ttf 10   50000 fonts/Arial.ttf 13    250000 fonts/Arial.ttf 18
FONTS_Z9=  0 fonts/Arial.ttf 10   50000 fonts/Arial.ttf 13    250000 fonts/Arial.ttf 18
FONTS_Z10= 0 fonts/Arial.ttf 10   50000 fonts/Arial.ttf 13    250000 fonts/Arial.ttf 18
FONTS_Z11= 0 fonts/Arial.ttf 10   50000 fonts/Arial.ttf 13    250000 fonts/Arial.ttf 18



all: \
	North-America-z4.txt North-America-z5.txt North-America-z6.txt.gz \
	North-America-z7.txt.gz North-America-z8.txt.gz North-America-z9.txt.gz \
	North-America-z10.txt.gz North-America-z11.txt.gz \
	Europe-z4.txt Europe-z5.txt Europe-z6.txt.gz Europe-z7.txt.gz \
	Europe-z8.txt.gz Europe-z9.txt.gz Europe-z10.txt.gz Europe-z11.txt.gz \
	South-America-z4.txt South-America-z5.txt South-America-z6.txt.gz \
	South-America-z7.txt.gz South-America-z8.txt.gz South-America-z9.txt.gz \
	South-America-z10.txt.gz South-America-z11.txt.gz \
	Asia-z4.txt Asia-z5.txt Asia-z6.txt.gz Asia-z7.txt.gz Asia-z8.txt.gz \
	Asia-z9.txt.gz Asia-z10.txt.gz Asia-z11.txt.gz \
	Africa-z4.txt Africa-z5.txt Africa-z6.txt.gz Africa-z7.txt.gz \
	Africa-z8.txt.gz Africa-z9.txt.gz Africa-z10.txt.gz Africa-z11.txt.gz \
	Australia-New-Zealand-z4.txt Australia-New-Zealand-z5.txt \
	Australia-New-Zealand-z6.txt.gz Australia-New-Zealand-z7.txt.gz \
	Australia-New-Zealand-z8.txt.gz Australia-New-Zealand-z9.txt.gz \
	Australia-New-Zealand-z10.txt.gz Australia-New-Zealand-z11.txt.gz




North-America-z4.txt: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z4) 4 $@

North-America-z5.txt: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z5) 5 $@

North-America-z6.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z6) 6 $@

North-America-z7.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z7) 7 $@

North-America-z8.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z8) 8 $@

North-America-z9.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z9) 9 $@

North-America-z10.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z10) 10 $@

North-America-z11.txt.gz: North-America-all.txt.gz
	python effectuate-zooms.py North-America-all.txt.gz $(FONTS_Z11) 11 $@



Europe-z4.txt: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z4) 4 $@

Europe-z5.txt: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z5) 5 $@

Europe-z6.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z6) 6 $@

Europe-z7.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z7) 7 $@

Europe-z8.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z8) 8 $@

Europe-z9.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z9) 9 $@

Europe-z10.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z10) 10 $@

Europe-z11.txt.gz: Europe-all.txt.gz
	python effectuate-zooms.py Europe-all.txt.gz $(FONTS_Z11) 11 $@



South-America-z4.txt: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z4) 4 $@

South-America-z5.txt: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z5) 5 $@

South-America-z6.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z6) 6 $@

South-America-z7.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z7) 7 $@

South-America-z8.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z8) 8 $@

South-America-z9.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z9) 9 $@

South-America-z10.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z10) 10 $@

South-America-z11.txt.gz: South-America-all.txt.gz
	python effectuate-zooms.py South-America-all.txt.gz $(FONTS_Z11) 11 $@



Asia-z4.txt: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z4) 4 $@

Asia-z5.txt: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z5) 5 $@

Asia-z6.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z6) 6 $@

Asia-z7.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z7) 7 $@

Asia-z8.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z8) 8 $@

Asia-z9.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z9) 9 $@

Asia-z10.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z10) 10 $@

Asia-z11.txt.gz: Asia-all.txt.gz
	python effectuate-zooms.py Asia-all.txt.gz $(FONTS_Z11) 11 $@



Africa-z4.txt: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z4) 4 $@

Africa-z5.txt: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z5) 5 $@

Africa-z6.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z6) 6 $@

Africa-z7.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z7) 7 $@

Africa-z8.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z8) 8 $@

Africa-z9.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z9) 9 $@

Africa-z10.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z10) 10 $@

Africa-z11.txt.gz: Africa-all.txt.gz
	python effectuate-zooms.py Africa-all.txt.gz $(FONTS_Z11) 11 $@



Australia-New-Zealand-z4.txt: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z4) 4 $@

Australia-New-Zealand-z5.txt: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z5) 5 $@

Australia-New-Zealand-z6.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z6) 6 $@

Australia-New-Zealand-z7.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z7) 7 $@

Australia-New-Zealand-z8.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z8) 8 $@

Australia-New-Zealand-z9.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z9) 9 $@

Australia-New-Zealand-z10.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z10) 10 $@

Australia-New-Zealand-z11.txt.gz: Australia-New-Zealand-all.txt.gz
	python effectuate-zooms.py Australia-New-Zealand-all.txt.gz $(FONTS_Z11) 11 $@
